task_manager/labels/urls.py
from django.urls import path

from .views import (
    LabelCreateView,
    LabelDeleteView,
    LabelListView,
    LabelUpdateView,
)

app_name = "labels"

urlpatterns = [
    path("", LabelListView.as_view(), name="list"),
    path("create/", LabelCreateView.as_view(), name="create"),
    path("<int:pk>/update/", LabelUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", LabelDeleteView.as_view(), name="delete"),
]

task_manager/tasks/urls.py
from django.urls import path

from .views import (
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskListView,
    TaskUpdateView,
)

app_name = "tasks"

urlpatterns = [
    path("", TaskListView.as_view(), name="list"),
    path("create/", TaskCreateView.as_view(), name="create"),
    path("<int:pk>/", TaskDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete"),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager.users.views import UserLoginView, UserLogoutView
from .views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("labels/", include("task_manager.labels.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
]

task_manager/users/urls.py
from django.urls import path

from .views import (
    UserCreateView,
    UserDeleteView,
    UserListView,
    UserUpdateView,
)

app_name = "users"

urlpatterns = [
    path("", UserListView.as_view(), name="list"),
    path("create/", UserCreateView.as_view(), name="create"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="delete"),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(_("Name"), max_length=150, unique=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)

    class Meta:
        ordering = ("pk",)
        verbose_name = _("Label")
        verbose_name_plural = _("Labels")

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django import forms

from .models import Label


class LabelForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True, label="Имя")

    class Meta:
        model = Label
        fields = ("name",)

task_manager/statuses/forms.py
from django import forms

from .models import Status


class StatusForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True, label="Имя")

    class Meta:
        model = Status
        fields = ("name",)

task_manager/tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model

from task_manager.labels.models import Label
from task_manager.statuses.models import Status

from .models import Task


class FullNameModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        full_name = obj.get_full_name()
        return full_name if full_name else obj.username


class TaskForm(forms.ModelForm):
    name = forms.CharField(max_length=150, required=True, label="Имя")
    description = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4}),
        required=False,
        label="Описание",
    )
    status = forms.ModelChoiceField(
        queryset=Status.objects.all(),
        label="Статус",
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    executor = FullNameModelChoiceField(
        queryset=get_user_model().objects.all(),
        required=False,
        label="Исполнитель",
        widget=forms.Select(attrs={"class": "form-select"}),
    )
    labels = forms.ModelMultipleChoiceField(
        queryset=Label.objects.all(),
        required=False,
        label="Метки",
        widget=forms.SelectMultiple(attrs={"class": "form-select"}),
    )

    class Meta:
        model = Task
        fields = ("name", "description", "status", "executor", "labels")

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label="Имя")
    last_name = forms.CharField(max_length=150, required=True, label="Фамилия")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, label="Имя")
    last_name = forms.CharField(max_length=150, required=True, label="Фамилия")
    password1 = forms.CharField(
        label="Пароль",
        strip=False,
        widget=forms.PasswordInput,
        required=False,
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        strip=False,
        widget=forms.PasswordInput,
        required=False,
    )

    class Meta:
        model = User
        fields = ("first_name", "last_name", "username")

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 or password2:
            if password1 != password2:
                raise forms.ValidationError("Введенные пароли не совпадают")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password1")
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=150,
        required=True,
        label="Имя пользователя",
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput,
        label="Пароль",
    )

task_manager/labels/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import LabelForm
from .models import Label
from task_manager.mixins import LoginMessageRequiredMixin


class SuccessMessageMixin:
    success_message = ""

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.success_message:
            messages.success(self.request, self.success_message)
        return response


class LabelListView(LoginMessageRequiredMixin, ListView):
    model = Label
    template_name = "labels/index.html"
    context_object_name = "labels"


class LabelCreateView(
    LoginMessageRequiredMixin,
    SuccessMessageMixin,
    CreateView,
):
    model = Label
    form_class = LabelForm
    template_name = "labels/form.html"
    success_url = reverse_lazy("labels:list")
    success_message = "Метка успешно создана"


class LabelUpdateView(
    LoginMessageRequiredMixin,
    SuccessMessageMixin,
    UpdateView,
):
    model = Label
    form_class = LabelForm
    template_name = "labels/form.html"
    success_url = reverse_lazy("labels:list")
    success_message = "Метка успешно изменена"


class LabelDeleteView(LoginMessageRequiredMixin, DeleteView):
    model = Label
    template_name = "labels/delete.html"
    success_url = reverse_lazy("labels:list")
    success_message = "Метка успешно удалена"
    protected_message = "Невозможно удалить метку, потому что она используется"

    def form_valid(self, form):
        self.object = self.get_object()
        success_url = self.get_success_url()
        if self.object.tasks.exists():
            messages.error(self.request, self.protected_message)
            return HttpResponseRedirect(success_url)
        self.object.delete()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(success_url)

task_manager/statuses/views.py
from django.contrib import messages
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView
from django.views.generic.edit import CreateView, UpdateView

from .forms import StatusForm
from .models import Status
from task_manager.mixins import LoginMessageRequiredMixin


class StatusListView(LoginMessageRequiredMixin, ListView):
    model = Status
    template_name = "statuses/index.html"
    context_object_name = "statuses"


class SuccessMessageMixin:
    success_message = ""

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.success_message:
            messages.success(self.request, self.success_message)
        return response


class StatusCreateView(
    LoginMessageRequiredMixin,
    SuccessMessageMixin,
    CreateView,
):
    model = Status
    form_class = StatusForm
    template_name = "statuses/form.html"
    success_url = reverse_lazy("statuses:list")
    success_message = "Статус успешно создан"


class StatusUpdateView(
    LoginMessageRequiredMixin,
    SuccessMessageMixin,
    UpdateView,
):
    model = Status
    form_class = StatusForm
    template_name = "statuses/form.html"
    success_url = reverse_lazy("statuses:list")
    success_message = "Статус успешно изменен"


class StatusDeleteView(LoginMessageRequiredMixin, DeleteView):
    model = Status
    template_name = "statuses/delete.html"
    success_url = reverse_lazy("statuses:list")
    success_message = "Статус успешно удален"
    protected_message = "Невозможно удалить статус, потому что он используется"

    def form_valid(self, form):
        self.object = self.get_object()
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.error(self.request, self.protected_message)
            return HttpResponseRedirect(success_url)
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(success_url)

task_manager/tasks/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django_filters.views import FilterView

from .forms import TaskForm
from .filters import TaskFilter
from .models import Task
from task_manager.mixins import LoginMessageRequiredMixin


class SuccessMessageMixin:
    success_message = ""

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.success_message:
            messages.success(self.request, self.success_message)
        return response


class AuthorRequiredMixin(LoginMessageRequiredMixin):
    permission_message = "Задачу может удалить только ее автор"

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)
        task = self.get_object()
        if task.author_id != request.user.id:
            messages.error(request, self.permission_message)
            return HttpResponseRedirect(reverse_lazy("tasks:list"))
        return super().dispatch(request, *args, **kwargs)


class TaskListView(
    LoginMessageRequiredMixin,
    FilterView,
):
    model = Task
    template_name = "tasks/index.html"
    context_object_name = "tasks"
    filterset_class = TaskFilter
    queryset = (
        Task.objects.select_related("status", "author", "executor")
        .prefetch_related("labels")
        .order_by("pk")
    )

    def get_filterset_kwargs(self, filterset_class):
        kwargs = super().get_filterset_kwargs(filterset_class)
        kwargs["request"] = self.request
        return kwargs


class TaskDetailView(
    LoginMessageRequiredMixin,
    DetailView,
):
    model = Task
    template_name = "tasks/detail.html"
    context_object_name = "task"
    queryset = (
        Task.objects.select_related("status", "author", "executor")
        .prefetch_related("labels")
    )


class TaskCreateView(
    LoginMessageRequiredMixin,
    SuccessMessageMixin,
    CreateView,
):
    model = Task
    form_class = TaskForm
    template_name = "tasks/form.html"
    success_url = reverse_lazy("tasks:list")
    success_message = "Задача успешно создана"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(
    LoginMessageRequiredMixin,
    SuccessMessageMixin,
    UpdateView,
):
    model = Task
    form_class = TaskForm
    template_name = "tasks/form.html"
    success_url = reverse_lazy("tasks:list")
    success_message = "Задача успешно изменена"
    queryset = (
        Task.objects.select_related("status", "author", "executor")
        .prefetch_related("labels")
    )


class TaskDeleteView(
    AuthorRequiredMixin,
    DeleteView,
):
    model = Task
    template_name = "tasks/delete.html"
    success_url = reverse_lazy("tasks:list")
    success_message = "Задача успешно удалена"
    queryset = (
        Task.objects.select_related("status", "author", "executor")
        .prefetch_related("labels")
    )

    def post(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return self.success_url

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, UpdateView
from django.views.generic.edit import CreateView

from .forms import UserLoginForm, UserRegisterForm, UserUpdateForm
from task_manager.mixins import LoginMessageRequiredMixin


class UserListView(ListView):
    model = User
    template_name = "users/index.html"
    context_object_name = "users"
    ordering = ("pk",)


class SuccessRedirectMixin:
    success_message = ""

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.success_message:
            messages.success(self.request, self.success_message)
        return response


class UserPermissionMixin(LoginMessageRequiredMixin):
    permission_message = "У вас нет прав для изменения другого пользователя."

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return super().dispatch(request, *args, **kwargs)

        if self.get_object().pk != request.user.pk:
            messages.error(request, self.permission_message)
            return HttpResponseRedirect(reverse_lazy("users:list"))

        return super().dispatch(request, *args, **kwargs)


class UserCreateView(SuccessRedirectMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/form.html"
    success_url = reverse_lazy("login")
    success_message = "Пользователь успешно зарегистрирован"


class UserUpdateView(UserPermissionMixin, SuccessRedirectMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = "users/form.html"
    success_url = reverse_lazy("users:list")
    success_message = "Пользователь успешно изменен"


class UserDeleteView(UserPermissionMixin, DeleteView):
    model = User
    template_name = "users/delete.html"
    success_url = reverse_lazy("users:list")
    success_message = "Пользователь успешно удален"
    protected_message = (
        "Невозможно удалить пользователя, потому что он используется"
    )

    def form_valid(self, form):
        self.object = self.get_object()
        success_url = self.get_success_url()
        try:
            self.object.delete()
        except ProtectedError:
            messages.error(self.request, self.protected_message)
            return HttpResponseRedirect(success_url)
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(success_url)


class UserLoginView(LoginView):
    template_name = "login.html"
    authentication_form = UserLoginForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Вы залогинены")
        return response

    def get_success_url(self):
        return self.get_redirect_url() or reverse_lazy("index")


class UserLogoutView(LogoutView):
    next_page = reverse_lazy("index")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(request, "Вы разлогинены")
        return super().dispatch(request, *args, **kwargs)

task_manager/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

task_manager/templates/tasks/delete.html
{% extends "base.html" %}

{% block title %}Удаление задачи{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card shadow-sm border-0">
        <div class="card-body">
          <h1 class="h4 mb-3 text-center">Удаление задачи</h1>
          <p class="mb-4 text-center">
            Вы уверены, что хотите удалить задачу <strong>{{ object.name }}</strong>?
          </p>
          <form method="post" class="d-flex justify-content-center gap-3">
            {% csrf_token %}
            <a class="btn btn-outline-secondary" href="{% url 'tasks:list' %}">Отмена</a>
            <button class="btn btn-danger" type="submit">Да, удалить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends "base.html" %}

{% block title %}{{ task.name }}{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <div class="card shadow-sm border-0">
        <div class="card-body p-4">
          <h1 class="h3 mb-3">{{ task.name }}</h1>
          <dl class="row">
            <dt class="col-sm-3">Статус</dt>
            <dd class="col-sm-9">{{ task.status.name }}</dd>

            <dt class="col-sm-3">Автор</dt>
            <dd class="col-sm-9">
              {{ task.author.get_full_name|default:task.author.username }}
            </dd>

            <dt class="col-sm-3">Исполнитель</dt>
            <dd class="col-sm-9">
              {% if task.executor %}
                {{ task.executor.get_full_name|default:task.executor.username }}
              {% else %}
                <span class="text-muted">Не назначен</span>
              {% endif %}
            </dd>

            <dt class="col-sm-3">Метки</dt>
            <dd class="col-sm-9">
              {% with labels=task.labels.all %}
                {% if labels %}
                  {% for label in labels %}
                    <span class="badge text-bg-secondary me-1">{{ label.name }}</span>
                  {% endfor %}
                {% else %}
                  <span class="text-muted">Не заданы</span>
                {% endif %}
              {% endwith %}
            </dd>

            <dt class="col-sm-3">Описание</dt>
            <dd class="col-sm-9">
              {% if task.description %}
                <p class="mb-0">{{ task.description|linebreaksbr }}</p>
              {% else %}
                <span class="text-muted">Отсутствует</span>
              {% endif %}
            </dd>
          </dl>
          <div class="d-flex gap-2">
            <a class="btn btn-outline-secondary" href="{% url 'tasks:update' task.pk %}">Изменить</a>
            {% if request.user.pk == task.author_id %}
              <a class="btn btn-danger" href="{% url 'tasks:delete' task.pk %}">Удалить</a>
            {% endif %}
            <a class="btn btn-link" href="{% url 'tasks:list' %}">Назад к списку</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/templates/tasks/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  {% if view.object %}
    Изменение задачи
  {% else %}
    Создание задачи
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-7">
      <h1 class="h3 mb-4 text-center">
        {% if view.object %}
          Изменение задачи
        {% else %}
          Новая задача
        {% endif %}
      </h1>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-grid">
          <button class="btn btn-primary" type="submit">
            {% if view.object %}Изменить{% else %}Создать{% endif %}
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

task_manager/templates/tasks/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Задачи{% endblock %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="h3 mb-0">Задачи</h1>
    <a class="btn btn-primary" href="{% url 'tasks:create' %}">Создать задачу</a>
  </div>
  {% if filter %}
    <form method="get" class="card card-body mb-4 shadow-sm">
      <div class="row g-3 align-items-end">
        <div class="col-md-3">
          {% bootstrap_field filter.form.status form_group_class="mb-0" show_help=False %}
        </div>
        <div class="col-md-3">
          {% bootstrap_field filter.form.executor form_group_class="mb-0" show_help=False %}
        </div>
        <div class="col-md-3">
          {% bootstrap_field filter.form.labels form_group_class="mb-0" show_help=False %}
        </div>
        <div class="col-md-3">
          {% bootstrap_field filter.form.my_tasks form_group_class="mb-0" show_help=False %}
        </div>
      </div>
      <div class="d-flex gap-2 mt-3">
        <button class="btn btn-primary" type="submit">Показать</button>
        <a class="btn btn-outline-secondary" href="{% url 'tasks:list' %}">Сбросить</a>
      </div>
    </form>
  {% endif %}
  <div class="table-responsive">
    <table class="table table-striped align-middle">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Имя</th>
          <th scope="col">Статус</th>
          <th scope="col">Автор</th>
          <th scope="col">Исполнитель</th>
          <th scope="col">Метки</th>
          <th scope="col" class="text-end">Действия</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
          <tr>
            <th scope="row">{{ task.pk }}</th>
            <td>
              <a href="{% url 'tasks:detail' task.pk %}" class="link-primary text-decoration-none">
                {{ task.name }}
              </a>
            </td>
            <td>{{ task.status.name }}</td>
            <td>{{ task.author.get_full_name|default:task.author.username }}</td>
            <td>
              {% if task.executor %}
                {{ task.executor.get_full_name|default:task.executor.username }}
              {% else %}
                <span class="text-muted">—</span>
              {% endif %}
            </td>
            <td>
              {% with labels=task.labels.all %}
                {% if labels %}
                  {% for label in labels %}
                    <span class="badge text-bg-secondary me-1">{{ label.name }}</span>
                  {% endfor %}
                {% else %}
                  <span class="text-muted">—</span>
                {% endif %}
              {% endwith %}
            </td>
            <td class="text-end">
              <a class="btn btn-sm btn-outline-secondary" href="{% url 'tasks:update' task.pk %}">Изменить</a>
              <a class="btn btn-sm btn-outline-danger ms-2" href="{% url 'tasks:delete' task.pk %}">Удалить</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="7" class="text-center py-4">Задачи отсутствуют.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}